name: Deploy PWA

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    concurrency:
      group: "pages"
      cancel-in-progress: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Оновлено до v3
        with:
          path: '.'  # Вказуємо корінь репозиторію
          
      - name: Deploy
        uses: actions/deploy-pages@v3  # Оновлено до v3
        timeout-minutes: 5
